AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo

  Sample SAM Template for todo

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        TODO_TABLE: !Ref TodoTable

Resources:
  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  ListTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: list.list_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        ListTodo:
          Type: Api
          Properties:
            Path: /todo
            Method: get

  CreateTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create.create_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        CreateTodo:
          Type: Api
          Properties:
            Path: /todo
            Method: post
  DeleteTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete.delete_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        DeleteTodo:
          Type: Api
          Properties:
            Path: /todo/{todo_id}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TodoApi:
    Description: "API Gateway endpoint URL for Prod stage for Todo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
