AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo

  Sample SAM Template for todo

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        TODO_TABLE: !Ref TodoTable
        USER_TABLE: !Ref UserTable
        REGION: 'ap-northeast-1'

Resources:
  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: TodoUserPool
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: CognitoClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  ConfirmUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ConfirmUserRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/
      Handler: create.create_user_handler
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /create
            Method: post
      Environment:
        Variables:
          USERPOOL_ID: !Ref CognitoUserPool
          CLIENT_ID: !Ref CognitoUserPoolClient

  ConfirmUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/
      Handler: confirm.confirm_handler
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /confirm
            Method: post
      Environment:
        Variables:
          USERPOOL_ID: !Ref CognitoUserPool
          CLIENT_ID: !Ref CognitoUserPoolClient
      Role: !GetAtt ConfirmUserRole.Arn

  AuthUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/auth/
      Handler: auth.auth_handler
      Events:
        AuthUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth
            Method: post
      Environment:
        Variables:
          CLIENT_ID: !Ref CognitoUserPoolClient

  ListTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/todo/
      Handler: list.list_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        ListTodo:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /todo
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

  CreateTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/todo/
      Handler: create.create_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        CreateTodo:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /todo
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/todo/
      Handler: update.update_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        UpdateTodo:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /todo/{todo_id}
            Method: put
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/todo/
      Handler: delete.delete_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        DeleteTodo:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /todo/{todo_id}
            Method: delete
            Auth:
              Authorizer: CognitoAuthorizer

  SearchTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/todo/
      Handler: search.search_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TodoTable
      Architectures:
        - x86_64
      Events:
        SearchTodo:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /todo/search/{word}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TodoApi:
    Description: "API Gateway endpoint URL for Prod stage for Todo function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/todo/"
